# Generated by Django 2.0.4 on 2018-04-19 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translatify_translate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phraserequest',
            name='translated_phrase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='translatify_translate.TranslatedPhrase'),
        ),
        migrations.AlterField(
            model_name='phraserequest',
            name='requested_phrase',
            field=models.CharField(max_length=500),
        ),
    ]
