# Generated by Django 2.0.4 on 2018-04-19 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translatify_translate', '0002_auto_20180419_1109'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='translatedphrase',
            unique_together={('input_phrase', 'input_language')},
        ),
    ]
