# Generated by Django 2.0.4 on 2018-04-20 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translatify_translate', '0003_auto_20180419_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phraserequest',
            name='requesting_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phrase_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
